kind: pipeline
type: kubernetes
name: dron8s-release

steps:
- name: go
  image: golang:1.15.2
  environment:
    GOOS: linux 
    GOARCH: amd64 
    CGO_ENABLED: "0"
  commands:
  - go build -o dron8s .

- name: docker
  image: plugins/docker
  settings:
    repo: bh90210/dron8s
    auto_tag: true
    username: bh90210
    password: 
      from_secret: password

trigger:
  event:
  - tag
  - push

---
kind: secret
name: password
get:
  path: drone-docker
  name: password

# create the password:
# echo -n "super-secure-password" > ./pass
# kubectl create secret generic drone-docker --from-file=password=./pass
# rm ./pass