kind: pipeline
type: kubernetes
name: dron8s-release

steps:
- name: Go Build
  image: golang:1.15.2
  environment:
    GOOS: linux 
    GOARCH: amd64 
    CGO_ENABLED: "0"
  commands:
  - go build -o dron8s .

- name: Docker Build & Push
  image: plugins/docker
  settings:
    repo: bh90210/dron8s
    tags:
      - latest
    auto_tag: true
    username: 
      from_secret: drone-docker-username
    password: 
      from_secret: drone-docker-password

trigger:
  event:
  - tag

---
kind: secret
name: drone-docker-username
get:
  path: drone-docker
  name: username

---
kind: secret
name: drone-docker-password
get:
  path: drone-docker
  name: password