kind: pipeline
type: kubernetes
name: dron8s-example

steps:
- name: out-of-cluster
  image: bh90210/dron8s:latest
  settings:
    yaml: ./HA-dgraph.yaml
    kubeconfig:
      from_secret: k8secret
---
# don't gorfet to create the secret first
# kubectl create secret generic dron8s --from-file=kubeconfig=$HOME/.kube/config
kind: secret
name: k8secret
get:
  path: dron8s
  name: kubeconfig
